### ISSUE TITLE
Facebook image is not high res

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#2]
Facebook simple login only allows 100x100 pictures to b displayed.

With Graph API it should be possible to show high res pictures.

Solution is to find a method to use high res pictures from facebook.

**Comment by a3rosol** [comment]
Proposed fix:
during registration, contact the facebook API using the following end point:
https://graph.facebook.com/{facebookprofileID}/picture?type=large&redirect=0&width=400

and AngularJS' $http.get()

This resolves to the following JSON:
```javascript
{
   "data": {
      "height": 319,
      "is_silhouette": false,
      "url": "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpf1/v/t1.0-1/s480x480/5_n.jpg",
      "width": 480
   }
}
```
All we need to do now, is to access data.url and push it to firebase

**Comment by chrissijan** [comment]
Resolved with recent commit.
$http get and saving to db
