### ISSUE TITLE
Data conversion issue with birthdate in settings page

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#36]
try saving with numerical value eg $scope.loginModel.birthdate.getTime()

**Comment by chrissijan** [comment]
Firebase is simply not saving the timestring that the date box returns... fuckers

**Comment by chrissijan** [comment]
Simply remove the possibility to edit birthdate
Make it non-editable and just convert the getTime-Number to some dates and we should be good.

**Comment by a3rosol** [comment]
is this issue closed?

**Comment by chrissijan** [comment]
Nope, still the issue with conversion from time in ms to correct time format for <class=date">

rsulting in
rror: [ngModel:datefmt] Expected `748216800000` to be a date

at settings page
