### ISSUE TITLE
check if hugg rating is working

### ISSUE THREAD

**Issue by a3rosol** [a3rosol/huggr#54]

**Comment by a3rosol** [comment]
Total rating doesn't get calculated - assigning to chris

**Comment by a3rosol** [comment]
total rating gets calculated now, but after saving it to firebase, it gets immediately deleted.
WEIRD! maybe binding problem? @chrissijan need help!

**Comment by chrissijan** [comment]
with my testing it didnt get deleted and the totalRating value was calculated accordingly.

Objects are reqRating, answerRating, totalRating in hugg/{huggid}
