### ISSUE TITLE
Android: bug free?

### ISSUE THREAD

**Issue by a3rosol** [a3rosol/huggr#63]

**Comment by chrissijan** [comment]
settings page not working (it won't be loaded for some reason)
notifications return error (same as in web)
no results are displayed (but console.logs are given
menu issues in profile

**Comment by chrissijan** [comment]
for settings page: 
ReferenceError: Camera is not defined
    at null.<anonymous> (file:///android_asset/www/js/controllers.js:830:30):

document.addEventListener("deviceready", function() {

        var options = {
            quality: 90,
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: Camera.PictureSourceType.CAMERA,

[...]

**Comment by a3rosol** [comment]
I’m installing the SDK right now, patience pls :)

-- 
Emil Abramov
Sent with Airmail

Am 21. Januar 2015 bei 20:00:59, Christian (notifications@github.com) schrieb:

for settings page:
ReferenceError: Camera is not defined
at null. (file:///android_asset/www/js/controllers.js:830:30):

document.addEventListener("deviceready", function() {

    var options = {
        quality: 90,
        destinationType: Camera.DestinationType.DATA_URL,
        sourceType: Camera.PictureSourceType.CAMERA,

[...]

**Comment by a3rosol** [comment]
@chrissijan everything seem to be working quite ok now. albeit extremly choppy, but thats just android :P
can you confirm?
