### ISSUE TITLE
test on iOS: revealed bugs!

### ISSUE THREAD

**Issue by a3rosol** [a3rosol/huggr#64]

**Comment by a3rosol** [comment]
following bugs were found: 
header bar of i need a hug is to big
camera: image too pixelated
profile: in tabs view -> tabs-top -> header is shown twice
chat: automagically scroll to bottom, keyboard is on top of input, input is too wide
about: request assistance popover glitchy after keyboard is shown

**Comment by a3rosol** [comment]
chat needs another look

**Comment by chrissijan** [comment]
meh, fuck it, close
