### ISSUE TITLE
use matrix api

### ISSUE THREAD

**Issue by a3rosol** [a3rosol/huggr#69]
![1](https://cloud.githubusercontent.com/assets/4525630/5828307/e35ad5f8-a102-11e4-9c88-25d5c90852a4.png)
![2](https://cloud.githubusercontent.com/assets/4525630/5828306/e3587948-a102-11e4-80b2-0200925486b6.png)
This is definetly more than 0.8km

**Comment by a3rosol** [comment]
should be fixed with 5684ec907fea5fcfaec4988849888cf0acf0f8b0
hopefully...

**Comment by chrissijan** [comment]
Please change to using GOogle Maps DistanceMatrix API
Result should contain distance in km and value, duration for walking & car

**Comment by a3rosol** [comment]
@ChristopherStumm please add this functionality until tonight :)
