### ISSUE TITLE
include inappbrowser (not working on android)

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#73]

**Comment by a3rosol** [comment]
please describe the issue

**Comment by chrissijan** [comment]
blank page without any options to go back or whatever after login popup
appears

**Comment by chrissijan** [comment]
self is the man (sorry to bother you)

but we should really consider on documenting all the plugins and stuff we install locally and don't sync

**Comment by a3rosol** [comment]
No worries, I think ionic platform add android 
should have sufficed

-- 
Emil Abramov
Sent with Airmail

Am 21. Januar 2015 bei 19:36:38, Christian (notifications@github.com) schrieb:

self is the man (sorry to bother you)

but we should really consider on documenting all the plugins and stuff we install locally and don't sync
