### ISSUE TITLE
fucking rating still not fucking working

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#79]

**Comment by chrissijan** [comment]
not seeing buttons for rating?

**Comment by a3rosol** [comment]
8fa55d3
please be advised: the rating still does not work as desired. the stars are shown, and people can give each other ratings. the following happens(person1, person2)
person1 views the done huggs page -> rating gets set to -1 initially
person2 views the done huggs page -> same
person1 rates -> everything allrigh, rating gets set
person2 rates -> weird! rating gets set, totalRating gets calculated and then deleted. after rating again, total rating is calculated again, and everything is fine.

any ideas?
