### ISSUE TITLE
map on front to display huggs in radius click to show result view

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#94]

**Comment by a3rosol** [comment]
please provide a method to get a synchronized array of all the huggs in the area, and I will do it ;)

**Comment by chrissijan** [comment]
Sure, will try to provide one in a couple of minutes

**Comment by chrissijan** [comment]
Is it possible to just use the existing huggArray and extend it with the
coordinates? So you could access those?

**Comment by chrissijan** [comment]
Provided method that returns lat and long for all huggs that are present in a 10 km radius
Filters are only blocked users and that you don't see your own huggs

**Comment by chrissijan** [comment]
zoom level needs to be lower

**Comment by chrissijan** [comment]
![image](https://cloud.githubusercontent.com/assets/5989913/5940956/54d4c1f6-a70e-11e4-811f-94ee1b029bfa.png)
Strange behaviour. First it gets my position correctly, then it snaps to ocean view...
