### ISSUE TITLE
change zoom factor if huggs have greater distance

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#96]
HOw it is : ![image](https://cloud.githubusercontent.com/assets/5989913/5886618/97b90874-a3a8-11e4-8246-90fc6b876400.png)

How it should be: 
![image](https://cloud.githubusercontent.com/assets/5989913/5886622/ac7e5f2a-a3a8-11e4-9c27-a290dd021961.png)

**Comment by a3rosol** [comment]
please test

**Comment by chrissijan** [comment]
After update:
![image](https://cloud.githubusercontent.com/assets/5989913/5887401/23d9a848-a3ce-11e4-8ce6-c90cbe05c94a.png)

Zoom factor is okay, but map needs to be centered somehow in the middle of the two

**Comment by a3rosol** [comment]
can you post request a hug, so i can work with your position?

**Comment by chrissijan** [comment]
sure just did a couple

**Comment by chrissijan** [comment]
beautiful <3
