### ISSUE TITLE
reduce data amount by creating 100x100 avatars

### ISSUE THREAD

**Issue by chrissijan** [a3rosol/huggr#99]
in result, chat and huggs we only show small pictures of the users, however the fullsize picture is loaded and then cropped. 
Is it possible to create a cropped photo of the user and store it on the external image server and only load those cropped avatars when they are needed? This would reduce the data usage.

**Comment by a3rosol** [comment]
on the mobile app (especially on ios) ionic makes heavy use of caching, so each image is actually loaded once. when using the ionic serve command, caching gets deactivated, since it can introduce a lot of problems during development. i don't recommend adding more complexity to this ;)

**Comment by chrissijan** [comment]
ok
